name: Create and Push File on Schedule

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *"  # This runs the workflow every day at midnight UTC

jobs:
  create_and_push_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Choose your desired Python version
      
      - name: Install Dependencies
        run: |
          pip install -r scr/requirements.txt
      
      - name: Run Python Script
        run: python scr/gen-article.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Create and Push File
        run: |
          ls
          git config --global user.name "Github Actions"
          git config --global user.email "colt.gainey@gmail.com"
          git add posts/*
          git commit -a -m "I'm sure these articles are accurate and not controversial"
          git push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
